import React, {createContext, useState} from 'react';

export const ItemsContext = createContext();

export const ItemsProvider = ({children}) => {
  const [items, setItems] = useState([
    {
      id: 1,
      name: 'Volkswagen Passat B8',
      color: 'dark',
      year: 1992,
      price: 1500,
      available: true,
      image: require('./images/passatb2.jpg'),
    },
    {
      id: 2,
      name: 'Polo amg',
      color: 'bright',
      year: 2000,
      price: 800,
      available: false,
      image: require('./images/polo.jpg'),
    },
    {
      id: 3,
      name: 'Audi Alien',
      color: 'normal',
      year: 2055,
      price: 15000,
      available: true,
      image: require('./images/alien.jpg'),
    },
    {
      id: 4,
      name: 'Big Foot на город',
      color: 'dark',
      year: 2005,
      price: 10000,
      available: false,
      image: require('./images/bigfoot.jpg'),
    },
    {
      id: 5,
      name: 'Легенькі підфарбування',
      color: 'dark',
      year: 2014,
      price: 6000,
      available: true,
      image: require('./images/junk.jpg'),
    },
    {
      id: 6,
      name: 'газ + бензин',
      color: 'bright',
      year: 2023,
      price: 100,
      available: true,
      image: require('./images/tesla.jpg'),
    },
    {
      id: 7,
      name: 'Toyota Supra MK4',
      color: 'classic',
      year: 1998,
      price: 13999,
      available: true,
      image: require('./images/supra.jpg'),
    },
    {
      id: 8,
      name: 'Honda Civic Type R',
      color: 'bright',
      year: 2019,
      price: 1200,
      available: true,
      image: require('./images/civic.jpg'),
    },
    {
      id: 9,
      name: 'BMW M3 E30',
      color: 'classic',
      year: 1990,
      price: 15001,
      available: false,
      image: require('./images/e30.jpeg'),
    },
    {
      id: 10,
      name: 'Mercedes G-Wagon',
      color: 'dark',
      year: 2001,
      price: 13333,
      available: true,
      image: require('./images/gclass.jpg'),
    },
    {
      id: 11,
      name: 'Chevrolet Camaro',
      color: 'bright',
      year: 2010,
      price: 1100,
      available: true,
      image: require('./images/camaro.jpg'),
    },
    {
      id: 12,
      name: 'Ford Mustang GT',
      color: 'bright',
      year: 2015,
      price: 9770,
      available: true,
      image: require('./images/gt5.jfif'),
    },
    {
      id: 13,
      name: 'Nissan Skyline GT-R',
      color: 'dark',
      year: 1999,
      price: 16579,
      available: false,
      image: require('./images/r34.jpg'),
    },
    {
      id: 14,
      name: 'Porsche 911',
      color: 'classic',
      year: 1995,
      price: 14596,
      available: true,
      image: require('./images/930.jpg'),
    },
    {
      id: 15,
      name: 'Mazda RX-7',
      color: 'normal',
      year: 2002,
      price: 12345,
      available: true,
      image: require('./images/rx7.jpeg'),
    },
    {
      id: 16,
      name: 'Subaru WRX',
      color: 'normal',
      year: 2010,
      price: 9500,
      available: true,
      image: require('./images/wrx.jpg'),
    },
    {
      id: 17,
      name: 'Dodge Charger',
      color: 'dark',
      year: 2008,
      price: 8000,
      available: true,
      image: require('./images/charger.jpg'),
    },
    {
      id: 18,
      name: 'Jaguar X-Type',
      color: 'classic',
      year: 2005,
      price: 7000,
      available: true,
      image: require('./images/xtype.jfif'),
    },
    {
      id: 19,
      name: 'Mazda Miata MX-5',
      color: 'bright',
      year: 2003,
      price: 5500,
      available: true,
      image: require('./images/miata.jfif'),
    },
    {
      id: 20,
      name: 'Hyundai Genesis',
      color: 'normal',
      year: 2012,
      price: 14345,
      available: false,
      image: require('./images/hyundai.jfif'),
    },
    {
      id: 21,
      name: 'Дізільний бус',
      color: 'bright',
      year: 2011,
      price: 20000,
      available: true,
      image: require('./images/disiel.jpg'),
    }

  ]);


  return (
    <ItemsContext.Provider value={{items, setItems}}>
      {children}
    </ItemsContext.Provider>
  );
};
